default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  host: localhost
  database: thunt_development

test:
  <<: *default
  database: thunt_test

production:
  <<: *default
  database: thunt_production
